version: '3.9'

services:
  db:
    image: postgres:15
    container_name: etl_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: etl_db
    volumes:
      - ./seeds:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  mock-api:
    build: ./mock_api
    container_name: mock_api
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/data"]
      interval: 5s
      retries: 5

  orchestrator:
    build: ./orchestrator
    container_name: orchestrator
    depends_on:
      db:
        condition: service_healthy
      mock-api:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./data:/data